spring:
  application:
    name: simple-products
  datasource:
    url: jdbc:postgresql://localhost:5432/simple-products
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/database-changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /simple-products/api

hnb:
  base-url: https://api.hnb.hr/tecajn-eur/v3

api:
  key: '49e75020-bec1-4b19-ad0c-6b47ec110b15'
